CC = gcc
CFLAGS = -std=gnu99 -g
SERVER_SOURCES = server.c task14.c
CLIENT_SOURCES = client.c task14.c
LIBRARIES = -lm

all:
	$(CC) $(CFLAGS) $(SERVER_SOURCES) $(LIBRARIES) -o Lab5_Server.o
	$(CC) $(CFLAGS) $(CLIENT_SOURCES) $(LIBRARIES) -o Lab5_Client.o
	
